---
# HEADER SECTION
 - name: This playbook will test forloop
   hosts: webservers
   vars:
     myfiles: ['file1.txt', 'file2.txt']
     mydir: ['webapp-1', 'webapp-2']

# TASK SECTION
   tasks:
     - name: To create 3 files
       file:
         path: /opt/{{ item }}
         state: file
         mode: 0600
       with_items: "{{ myfiles }}"

     - name: To create 2 directories
       file:
         path: /opt/{{ item }}
         state: directory
         mode: 0644
         recurse: yes
         owner: ec2-user
         group: ec2-user
       with_items: "{{ mydir }}"

# Learn Ignore errors
#       ignore_errors: yes
