---
# This is my first playbook

# HEADER SECTION
 - name: This playbook will create a file
   hosts: webservers
   vars:
     abc: Goutham

# TASK SECTION
   tasks:
     - name: To print the value of the file inventory.txt
       command: cat /opt/abc.txt
       register: output

     - name: To print a value of a variable
       debug:
         var: output

     - name: To print a value of a variable
       debug:
         var: abc

     - name: to print only value of rc
       debug:
         var: output.rc

     - name: to print only value of stdout_lines
       debug:
         var: output.stdout_lines

     - name: To Uninstall packages using the data from the Output of command module
       yum:
         name: "{{ item }}"
         state: installed
       with_items: "{{ output.stdout_lines }}"

     - name: To check whether my command module ran sucessfully or not
       file:
         path: /opt/sucess.txt
         state: touch
       when: output.rc == 1
