---
# HEADER SECTION
 - name: This playbook will test forloop
   hosts: webservers

# TASK SECTION
   tasks:
     - name: To create 3 files
       file:
         path: /opt/{{ item }}
         state: touch
         mode: 0644
         owner: ubuntu
         group: ubuntu
       with_items:
         - file1.txt
         - file2.txt
         - myfile.sh

     - name: To install 2 packages
       apt:
         name: ['wget', 'unzip']
         state: present
