---
# This Playbook will define vairables and use them across the code

# HEADER SECTION
 - name: This playbook will install a package and create a file
   hosts: webservers
   vars:
     mypackage: vim
     myfile: helloworld.txt

# TASK SECTION
   tasks:
     - name: To install package named "{{ mypackage }}"
       yum:
         name: "{{ mypackage }}"
         state: installed

     - name: To create a file named "{{ myfile }}"
       file:
         path: /opt/{{ myfile }}
         state: file
